// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RH.EntityFramework.Shared.DbContexts;

namespace RH.EntityFramework.Shared.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20200829090929_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RH.EntityFramework.Shared.Entities.Dimension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<short>("X")
                        .HasColumnType("smallint");

                    b.Property<short>("Y")
                        .HasColumnType("smallint");

                    b.Property<short>("Zoom")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Dimensions");
                });

            modelBuilder.Entity("RH.EntityFramework.Shared.Entities.Forecast", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DimensionId")
                        .HasColumnType("int");

                    b.Property<string>("ECMWFContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GFSContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Start")
                        .HasColumnType("bigint");

                    b.Property<short>("Step")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DimensionId");

                    b.ToTable("Forecasts");
                });

            modelBuilder.Entity("RH.EntityFramework.Shared.Entities.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DimensionId")
                        .HasColumnType("int");

                    b.Property<int>("ExtraField1")
                        .HasColumnType("int");

                    b.Property<int>("ExtraField2")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("O")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DimensionId");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("RH.EntityFramework.Shared.Entities.Forecast", b =>
                {
                    b.HasOne("RH.EntityFramework.Shared.Entities.Dimension", "Dimension")
                        .WithMany("Forecasts")
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RH.EntityFramework.Shared.Entities.Label", b =>
                {
                    b.HasOne("RH.EntityFramework.Shared.Entities.Dimension", "Dimension")
                        .WithMany("Labels")
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
